# -*- coding: utf-8 -*-
"""vision competition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wG9-HL4I2whhhFx89UWotjUc8dPKXXAO
"""

# ============================================================
# Cell 1 — Install required libraries
# ============================================================

!pip install -q ultralytics
!pip install -q transformers accelerate
!pip install -q torch torchvision

# ============================================================
# Cell 2 — Mount Google Drive
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# Cell 3 — Import libraries
# ============================================================

import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from collections import Counter
from ultralytics import YOLO
from transformers import CLIPProcessor, CLIPModel
import torch.nn.functional as F

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

# ============================================================
# Cell 4 — Check few-shot folder in Google Drive
# ============================================================

few_shot_dir = "/content/drive/MyDrive/restaurant_few_shot"

if not os.path.exists(few_shot_dir):
    raise FileNotFoundError(f"Few-shot folder not found: {few_shot_dir}")

print("Few-shot folder found:")
print(few_shot_dir)

print("\nFolders and image counts:")
print("-------------------------")

for folder in sorted(os.listdir(few_shot_dir)):
    folder_path = os.path.join(few_shot_dir, folder)

    if os.path.isdir(folder_path):
        image_files = [
            f for f in os.listdir(folder_path)
            if f.lower().endswith((".jpg", ".jpeg", ".png"))
        ]

        print(f"{folder:30s} -> {len(image_files)} images")

# ============================================================
# Cell 5 — Load CLIP model for few-shot image embeddings
# ============================================================

clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

print("CLIP model loaded on:", device)

# ============================================================
# Cell 6 — Define corrected CLIP image embedding function
# ============================================================

def get_clip_image_embedding(pil_image):
    """
    Creates a normalized CLIP image embedding.
    This version works correctly with transformers CLIPModel.
    """

    inputs = clip_processor(
        images=pil_image,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = clip_model.vision_model(
            pixel_values=inputs["pixel_values"]
        )

        image_features = outputs.pooler_output
        image_features = clip_model.visual_projection(image_features)

    image_features = F.normalize(image_features, p=2, dim=-1)

    return image_features

# ============================================================
# Cell 7 — Build few-shot reference embeddings from Google Drive
# ============================================================

few_shot_labels = {
    "sandwich": "sandwich",
    "slice_of_pie": "slice of pie",
    "hot_dog": "hot dog",
    "crisps": "crisps",
    "chocolate_chip_cookie": "chocolate chip cookie",
    "waffle": "waffle",
    "bacon": "bacon",
    "crab": "crab",
    "lemon": "lemon",
    "slice_of_pizza": "slice of pizza",
    "prawn": "prawn",
    "tomato_ketchup_bottle": "tomato ketchup bottle",
    "yellow_mustard_bottle": "yellow mustard bottle"
}

reference_embeddings = {}
reference_texts = {}

print("Building few-shot reference embeddings...")
print("-----------------------------------------")

for folder_name, text_label in few_shot_labels.items():
    folder_path = os.path.join(few_shot_dir, folder_name)

    if not os.path.exists(folder_path):
        print("Missing folder:", folder_name)
        continue

    image_files = [
        f for f in os.listdir(folder_path)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if len(image_files) == 0:
        print("No images in:", folder_name)
        continue

    embeddings = []

    for file in image_files:
        image_path = os.path.join(folder_path, file)

        try:
            img = Image.open(image_path).convert("RGB")
            emb = get_clip_image_embedding(img)
            embeddings.append(emb)

        except Exception as e:
            print("Could not read:", image_path)
            print(e)

    if len(embeddings) > 0:
        all_embeddings = torch.cat(embeddings, dim=0)

        mean_embedding = torch.mean(all_embeddings, dim=0, keepdim=True)
        mean_embedding = F.normalize(mean_embedding, p=2, dim=-1)

        reference_embeddings[folder_name] = mean_embedding
        reference_texts[folder_name] = text_label

        print(folder_name, "loaded with", len(embeddings), "images")

print("\nFinal few-shot classes loaded:")
print(list(reference_embeddings.keys()))

if len(reference_embeddings) == 0:
    raise ValueError("No few-shot embeddings loaded. Check folder names and images.")
else:
    print("\nSUCCESS: Few-shot embeddings loaded correctly.")

# ============================================================
# Cell 8 — Quick test of few-shot embeddings
# ============================================================

def classify_image_with_few_shot(pil_image, top_k=10):
    """
    Compares an image/crop with your few-shot reference embeddings.
    """

    if len(reference_embeddings) == 0:
        return None, []

    image_emb = get_clip_image_embedding(pil_image)

    scores = []

    for label, ref_emb in reference_embeddings.items():
        score = torch.matmul(image_emb, ref_emb.T).item()
        scores.append((label, score))

    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    best_result = scores[0] if len(scores) > 0 else None
    top_scores = scores[:top_k]

    return best_result, top_scores


# Test using one saved hot dog image if available
test_folder = os.path.join(few_shot_dir, "hot_dog")

if os.path.exists(test_folder):
    test_images = [
        f for f in os.listdir(test_folder)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    ]

    if len(test_images) > 0:
        test_image_path = os.path.join(test_folder, test_images[0])
        test_img = Image.open(test_image_path).convert("RGB")

        best_result, top_scores = classify_image_with_few_shot(test_img, top_k=5)

        print("Few-shot test image:")
        print(test_image_path)
        print("\nBest result:")
        print(best_result)

        print("\nTop scores:")
        for label, score in top_scores:
            print(label, round(score, 3))

        display(test_img)
    else:
        print("No test images found in hot_dog folder.")
else:
    print("hot_dog folder not found.")

# ============================================================
# Cell 9 — Load YOLO models
# ============================================================

# Reliable COCO model for people and dining tables
people_table_model = YOLO("yolov8m.pt")

# Open-vocabulary YOLO model for special objects
object_model = YOLO("yolov8s-world.pt")

objects_i_want = [
    "sandwich",
    "slice of pie",
    "pie",
    "hot dog",
    "toy hot dog",
    "plastic hot dog",
    "crisps",
    "potato chips",
    "chocolate chip cookie",
    "cookie",
    "waffle",
    "bacon",
    "crab",
    "lemon",
    "slice of pizza",
    "pizza",
    "prawn",
    "shrimp",
    "tomato ketchup bottle",
    "ketchup bottle",
    "yellow mustard bottle",
    "mustard bottle",
    "bottle"
]

object_model.set_classes(objects_i_want)

print("YOLO models loaded.")
print("\nPeople/table model:")
print("yolov8m.pt")

print("\nSpecial object model:")
print("yolov8s-world.pt")

print("\nSpecial object classes:")
print(objects_i_want)

# ============================================================
# Cell 10 — Webcam capture function
# ============================================================

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename="/content/webcam_photo.jpg", quality=0.9):
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');

            const instruction = document.createElement('p');
            instruction.textContent = 'Show the restaurant scene/object clearly, then click Capture photo.';
            instruction.style.fontSize = '18px';
            instruction.style.fontWeight = 'bold';
            div.appendChild(instruction);

            const capture = document.createElement('button');
            capture.textContent = 'Capture photo';
            capture.style.fontSize = '18px';
            capture.style.padding = '10px';
            div.appendChild(capture);

            const video = document.createElement('video');
            video.style.display = 'block';
            video.style.marginTop = '10px';
            video.style.maxWidth = '640px';

            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            document.body.appendChild(div);
            div.appendChild(video);

            video.srcObject = stream;
            await video.play();

            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

            await new Promise((resolve) => capture.onclick = resolve);

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;

            canvas.getContext('2d').drawImage(video, 0, 0);

            stream.getVideoTracks()[0].stop();
            div.remove();

            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')

    display(js)
    data = eval_js('takePhoto({})'.format(quality))

    binary = b64decode(data.split(',')[1])

    with open(filename, 'wb') as f:
        f.write(binary)

    return filename

# ============================================================
# Cell 11 — Helper functions for boxes, labels, people, tables
# ============================================================

def box_area(box):
    x1, y1, x2, y2 = box
    return max(0, x2 - x1) * max(0, y2 - y1)


def box_area_ratio(box, frame):
    return box_area(box) / (frame.shape[0] * frame.shape[1])


def compute_iou(box1, box2):
    x1a, y1a, x2a, y2a = box1
    x1b, y1b, x2b, y2b = box2

    inter_x1 = max(x1a, x1b)
    inter_y1 = max(y1a, y1b)
    inter_x2 = min(x2a, x2b)
    inter_y2 = min(y2a, y2b)

    inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)

    area1 = max(1, box_area(box1))
    area2 = max(1, box_area(box2))

    union = area1 + area2 - inter_area

    return inter_area / union


def inside_ratio(inner_box, outer_box):
    x1a, y1a, x2a, y2a = inner_box
    x1b, y1b, x2b, y2b = outer_box

    inter_x1 = max(x1a, x1b)
    inter_y1 = max(y1a, y1b)
    inter_x2 = min(x2a, x2b)
    inter_y2 = min(y2a, y2b)

    inter_area = max(0, inter_x2 - inter_x1) * max(0, inter_y2 - inter_y1)

    inner_area = max(1, box_area(inner_box))

    return inter_area / inner_area


def clean_person_boxes(raw_people, frame_shape, iou_threshold=0.25, inside_threshold=0.50):
    """
    Removes duplicate person boxes.
    Important for avoiding one person being counted as 2 or 3 people.
    """

    h, w = frame_shape[:2]
    frame_area = h * w

    candidates = []

    for det in raw_people:
        box = det["box"]
        conf = det["confidence"]

        area_ratio = box_area(box) / frame_area
        x1, y1, x2, y2 = box
        height = y2 - y1

        if conf < 0.25:
            continue

        if area_ratio < 0.01:
            continue

        if height < h * 0.12:
            continue

        candidates.append(det)

    candidates = sorted(candidates, key=lambda d: d["confidence"], reverse=True)

    kept = []

    for det in candidates:
        duplicate = False

        for kept_det in kept:
            iou = compute_iou(det["box"], kept_det["box"])
            inside_1 = inside_ratio(det["box"], kept_det["box"])
            inside_2 = inside_ratio(kept_det["box"], det["box"])

            if iou >= iou_threshold or inside_1 >= inside_threshold or inside_2 >= inside_threshold:
                duplicate = True
                break

        if not duplicate:
            kept.append(det)

    return kept


def clean_duplicate_object_boxes(object_detections, iou_threshold=0.35):
    """
    Removes duplicate object boxes with same final label.
    """

    if len(object_detections) == 0:
        return []

    def detection_score(det):
        if det.get("fewshot_score") is not None:
            return det["fewshot_score"]
        return det["yolo_confidence"]

    detections = sorted(object_detections, key=detection_score, reverse=True)

    kept = []

    for det in detections:
        duplicate = False

        for kept_det in kept:
            same_label = det["final_label"] == kept_det["final_label"]
            iou = compute_iou(det["box"], kept_det["box"])
            inside_1 = inside_ratio(det["box"], kept_det["box"])
            inside_2 = inside_ratio(kept_det["box"], det["box"])

            if same_label and (iou > iou_threshold or inside_1 > 0.65 or inside_2 > 0.65):
                duplicate = True
                break

        if not duplicate:
            kept.append(det)

    return kept


def normalize_item_name(name):
    name = name.lower().strip()

    mapping = {
        "slice of pizza": "slice_of_pizza",
        "pizza": "slice_of_pizza",

        "slice of pie": "slice_of_pie",
        "pie": "slice_of_pie",

        "potato chips": "crisps",
        "crisps": "crisps",

        "chocolate chip cookie": "chocolate_chip_cookie",
        "cookie": "chocolate_chip_cookie",

        "shrimp": "prawn",
        "prawn": "prawn",

        "tomato ketchup bottle": "tomato_ketchup_bottle",
        "ketchup bottle": "tomato_ketchup_bottle",

        "yellow mustard bottle": "yellow_mustard_bottle",
        "mustard bottle": "yellow_mustard_bottle",

        "hot dog": "hot_dog",
        "toy hot dog": "hot_dog",
        "plastic hot dog": "hot_dog",

        "dining table": "table",
        "table": "table",
        "bottle": "bottle",
        "person": "person"
    }

    return mapping.get(name, name.replace(" ", "_"))


def display_label_name(name):
    mapping = {
        "slice_of_pizza": "slice of pizza",
        "slice_of_pie": "slice of pie",
        "chocolate_chip_cookie": "chocolate chip cookie",
        "tomato_ketchup_bottle": "tomato ketchup bottle",
        "yellow_mustard_bottle": "yellow mustard bottle",
        "hot_dog": "hot dog"
    }

    return mapping.get(name, name.replace("_", " "))


def crop_box_from_frame(frame, box, padding=8):
    x1, y1, x2, y2 = box

    h, w = frame.shape[:2]

    x1 = max(0, int(x1) - padding)
    y1 = max(0, int(y1) - padding)
    x2 = min(w, int(x2) + padding)
    y2 = min(h, int(y2) + padding)

    crop = frame[y1:y2, x1:x2]

    if crop.size == 0:
        return None

    crop_rgb = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
    return Image.fromarray(crop_rgb)

# ============================================================
# Cell 12 — Helper functions for free/occupied table detection
# ============================================================

def horizontal_overlap_ratio(box1, box2):
    x1a, y1a, x2a, y2a = box1
    x1b, y1b, x2b, y2b = box2

    overlap = max(0, min(x2a, x2b) - max(x1a, x1b))
    smaller_width = min(x2a - x1a, x2b - x1b)

    if smaller_width <= 0:
        return 0

    return overlap / smaller_width


def vertical_gap_between_boxes(box1, box2):
    x1a, y1a, x2a, y2a = box1
    x1b, y1b, x2b, y2b = box2

    if y2a < y1b:
        return y1b - y2a
    elif y2b < y1a:
        return y1a - y2b
    else:
        return 0


def is_person_near_table(table_box, people_detections):
    """
    A table is occupied if a person overlaps horizontally with it
    and is vertically close enough.
    """

    for person in people_detections:
        person_box = person["box"]

        h_overlap = horizontal_overlap_ratio(person_box, table_box)
        v_gap = vertical_gap_between_boxes(person_box, table_box)

        px1, py1, px2, py2 = person_box
        tx1, ty1, tx2, ty2 = table_box

        person_bottom = py2

        horizontal_condition = h_overlap > 0.20
        vertical_condition = v_gap < 150
        seated_condition = person_bottom > ty1 - 120

        if horizontal_condition and vertical_condition and seated_condition:
            return True

    return False


def object_center_inside_or_near_table(object_box, table_box, margin=70):
    ox1, oy1, ox2, oy2 = object_box
    tx1, ty1, tx2, ty2 = table_box

    cx = (ox1 + ox2) / 2
    cy = (oy1 + oy2) / 2

    return (
        tx1 - margin <= cx <= tx2 + margin and
        ty1 - margin <= cy <= ty2 + margin
    )


def table_has_objects(table_box, object_detections):
    objects_on_table = []

    for obj in object_detections:
        if object_center_inside_or_near_table(obj["box"], table_box, margin=70):
            objects_on_table.append(obj["final_label"])

    return len(objects_on_table) > 0, objects_on_table

# ============================================================
# Cell 13 — Final detection after webcam capture
# ============================================================

# -----------------------------
# Capture image
# -----------------------------

filename = take_photo("/content/final_restaurant_test.jpg")

frame = cv2.imread(filename)

if frame is None:
    raise ValueError("Image was not captured correctly. Please run the cell again.")

frame = cv2.resize(frame, (640, 480))
h, w = frame.shape[:2]

print("Image captured successfully.")
print("Image size:", frame.shape)

# -----------------------------
# A) People + table detection
# -----------------------------

people_table_results = people_table_model.predict(
    frame,
    conf=0.20,
    iou=0.45,
    imgsz=1280,
    device="cpu",
    verbose=False
)

raw_people = []
raw_tables = []

for r in people_table_results:
    for box in r.boxes:
        cls = int(box.cls[0])
        name = people_table_model.names[cls]
        conf = float(box.conf[0])
        xyxy = box.xyxy[0].cpu().numpy().astype(int).tolist()

        if name == "person":
            raw_people.append({
                "class": "person",
                "confidence": conf,
                "box": xyxy
            })

        elif name == "dining table":
            raw_tables.append({
                "final_label": "table",
                "final_label_display": "table",
                "decision_source": "YOLOv8m",
                "yolo_label": "dining table",
                "yolo_confidence": conf,
                "box": xyxy
            })

people_detections = clean_person_boxes(
    raw_people,
    frame_shape=frame.shape,
    iou_threshold=0.25,
    inside_threshold=0.50
)

table_detections = clean_duplicate_object_boxes(
    raw_tables,
    iou_threshold=0.40
)

used_fallback_table = False

if len(table_detections) == 0:
    fallback_table_box = [
        int(w * 0.05),
        int(h * 0.58),
        int(w * 0.98),
        int(h * 0.98)
    ]

    table_detections.append({
        "final_label": "table",
        "final_label_display": "table",
        "decision_source": "fallback",
        "yolo_label": "fallback table area",
        "yolo_confidence": 1.0,
        "box": fallback_table_box
    })

    used_fallback_table = True

# -----------------------------
# B) Special object detection
# -----------------------------

object_results = object_model.predict(
    frame,
    conf=0.03,
    iou=0.45,
    imgsz=1280,
    device="cpu",
    verbose=False
)

SPECIAL_CLASSES = [
    "sandwich",
    "slice_of_pie",
    "hot_dog",
    "crisps",
    "chocolate_chip_cookie",
    "waffle",
    "bacon",
    "crab",
    "lemon",
    "slice_of_pizza",
    "prawn",
    "tomato_ketchup_bottle",
    "yellow_mustard_bottle"
]

FEWSHOT_THRESHOLD = 0.78
FEWSHOT_MARGIN = 0.05

raw_object_detections = []

for r in object_results:
    for box in r.boxes:
        cls_id = int(box.cls[0])
        yolo_conf = float(box.conf[0])
        xyxy = box.xyxy[0].cpu().numpy().astype(int).tolist()

        yolo_label_raw = object_results[0].names[cls_id]
        yolo_label_norm = normalize_item_name(yolo_label_raw)

        area_ratio = box_area_ratio(xyxy, frame)

        # Avoid huge boxes that include person/background
        if area_ratio > 0.35:
            continue

        crop = crop_box_from_frame(frame, xyxy, padding=8)

        fewshot_label = None
        fewshot_score = None
        fewshot_margin = None
        fewshot_top_scores = []

        final_label = yolo_label_norm
        decision_source = "YOLO-World"

        # Use few-shot embeddings from Google Drive
        if crop is not None and len(reference_embeddings) > 0:
            best_result, all_scores = classify_image_with_few_shot(crop, top_k=20)

            filtered_scores = [
                (label, score)
                for label, score in all_scores
                if label in SPECIAL_CLASSES
            ]

            filtered_scores = sorted(filtered_scores, key=lambda x: x[1], reverse=True)
            fewshot_top_scores = filtered_scores[:5]

            if len(filtered_scores) > 0:
                fewshot_label, fewshot_score = filtered_scores[0]

                if len(filtered_scores) > 1:
                    fewshot_margin = fewshot_score - filtered_scores[1][1]
                else:
                    fewshot_margin = fewshot_score

                if fewshot_score >= FEWSHOT_THRESHOLD and fewshot_margin >= FEWSHOT_MARGIN:
                    final_label = fewshot_label
                    decision_source = "Few-shot CLIP"

        useful_label = final_label in SPECIAL_CLASSES or final_label == "bottle"

        if useful_label:
            raw_object_detections.append({
                "final_label": final_label,
                "final_label_display": display_label_name(final_label),
                "decision_source": decision_source,
                "yolo_label": yolo_label_raw,
                "yolo_label_norm": yolo_label_norm,
                "yolo_confidence": yolo_conf,
                "fewshot_label": fewshot_label,
                "fewshot_label_display": None if fewshot_label is None else display_label_name(fewshot_label),
                "fewshot_score": fewshot_score,
                "fewshot_margin": fewshot_margin,
                "fewshot_top_scores": fewshot_top_scores,
                "area_ratio": area_ratio,
                "box": xyxy
            })

object_detections = clean_duplicate_object_boxes(
    raw_object_detections,
    iou_threshold=0.35
)

# -----------------------------
# C) Table status
# -----------------------------

table_statuses = []

occupied_tables = 0
free_tables = 0

for idx, table in enumerate(table_detections):
    table_box = table["box"]

    occupied_by_person = is_person_near_table(table_box, people_detections)
    occupied_by_objects, objects_on_table = table_has_objects(table_box, object_detections)

    occupied = occupied_by_person or occupied_by_objects

    if occupied:
        status = "occupied"
        occupied_tables += 1
    else:
        status = "free"
        free_tables += 1

    table_statuses.append({
        "table_id": idx + 1,
        "status": status,
        "occupied_by_person": occupied_by_person,
        "occupied_by_objects": occupied_by_objects,
        "objects_on_table": objects_on_table,
        "box": table_box,
        "source": table["decision_source"]
    })

# -----------------------------
# D) Counts
# -----------------------------

people_count = len(people_detections)
table_count = len(table_detections)
object_counts = Counter([obj["final_label_display"] for obj in object_detections])

# -----------------------------
# E) Print results clearly
# -----------------------------

print("\nFINAL SUMMARY")
print("=============")
print("People count:", people_count)
print("Tables count:", table_count)
print("Occupied tables:", occupied_tables)
print("Free tables:", free_tables)

if used_fallback_table:
    print("Note: No dining table detected by YOLO, so fallback table region was used.")

print("\nObject counts:")
print("--------------")
if len(object_counts) == 0:
    print("No special objects detected.")
else:
    for name, count in object_counts.items():
        print(f"{name}: {count}")

print("\nPeople details:")
print("---------------")
print("Raw person boxes:", len(raw_people))
print("Clean person boxes:", len(people_detections))

for p in people_detections:
    print("person | conf:", round(p["confidence"], 3), "| box:", p["box"])

print("\nTable details:")
print("--------------")
for t in table_statuses:
    readable_objects = [display_label_name(x) for x in t["objects_on_table"]]

    print(
        f"Table {t['table_id']}: {t['status']} | "
        f"person nearby: {t['occupied_by_person']} | "
        f"objects nearby: {readable_objects} | "
        f"source: {t['source']}"
    )

print("\nObject details:")
print("---------------")

for obj in object_detections:
    print("Final:", obj["final_label_display"])
    print("Source:", obj["decision_source"])
    print("YOLO:", obj["yolo_label"], "| conf:", round(obj["yolo_confidence"], 3))

    if obj["fewshot_label"] is not None:
        print(
            "Few-shot best:",
            obj["fewshot_label_display"],
            "| score:",
            round(obj["fewshot_score"], 3),
            "| margin:",
            round(obj["fewshot_margin"], 3)
        )

        print("Few-shot top scores:")
        for label, score in obj["fewshot_top_scores"]:
            print("  ", display_label_name(label), ":", round(score, 3))
    else:
        print("Few-shot: not used")

    print("Box:", obj["box"])
    print("-" * 35)

# ============================================================
# Cell 14 — Draw final annotated image
# ============================================================

frame_draw = frame.copy()

# Draw tables
for t in table_statuses:
    x1, y1, x2, y2 = t["box"]

    if t["status"] == "occupied":
        color = (0, 0, 255)
        label = f"Table {t['table_id']}: occupied"
    else:
        color = (0, 255, 255)
        label = f"Table {t['table_id']}: free"

    cv2.rectangle(frame_draw, (x1, y1), (x2, y2), color, 2)

    cv2.putText(
        frame_draw,
        label,
        (x1, max(y1 - 8, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        color,
        2
    )

# Draw people
for p in people_detections:
    x1, y1, x2, y2 = p["box"]

    cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (0, 255, 0), 2)

    cv2.putText(
        frame_draw,
        f"person {p['confidence']:.2f}",
        (x1, max(y1 - 8, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (0, 255, 0),
        2
    )

# Draw objects
for obj in object_detections:
    x1, y1, x2, y2 = obj["box"]

    label = obj["final_label_display"]

    if obj["fewshot_score"] is not None:
        score = obj["fewshot_score"]
    else:
        score = obj["yolo_confidence"]

    cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (255, 0, 255), 2)

    cv2.putText(
        frame_draw,
        f"{label} {score:.2f}",
        (x1, max(y1 - 8, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (255, 0, 255),
        2
    )

# Draw summary
summary_lines = [
    f"People: {people_count}",
    f"Tables: {table_count}",
    f"Occupied: {occupied_tables}",
    f"Free: {free_tables}"
]

y = 35

for line in summary_lines:
    cv2.putText(
        frame_draw,
        line,
        (20, y),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.85,
        (255, 255, 255),
        3
    )
    y += 35

# Draw object counts
for name, count in object_counts.items():
    cv2.putText(
        frame_draw,
        f"{name}: {count}",
        (20, y),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.70,
        (255, 0, 255),
        2
    )
    y += 30

frame_rgb = cv2.cvtColor(frame_draw, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(12, 8))
plt.imshow(frame_rgb)
plt.axis("off")
plt.show()

# ============================================================
# Cell 13B — Clean final result with object count
# ============================================================

# Total number of detected objects
total_objects_count = sum(object_counts.values())

# Convert object counts into a readable list
if len(object_counts) == 0:
    objects_summary = "none"
else:
    object_parts = []

    for object_name, count in object_counts.items():
        object_parts.append(f"{object_name}: {count}")

    objects_summary = ", ".join(object_parts)

print("\nCLEAN FINAL RESULT")
print("==================")
print(f"people: {people_count}")
print(f"objects count: {total_objects_count}")
print(f"objects: {objects_summary}")
print(f"table occupied: {occupied_tables}")
print(f"free table: {free_tables}")

# ============================================================
# Cell 16 — Define robot restaurant menu requirements
# ============================================================

from collections import Counter
import pandas as pd

# Menu requirements based on the uploaded restaurant menu PDF
# Internal names must match your detector's normalized labels.

MENU_REQUIREMENTS = {
    "Menu 1": {
        "sandwich": 1,
        "slice_of_pie": 1
    },

    "Menu 2": {
        "hot_dog": 1,
        "crisps": 1,
        "chocolate_chip_cookie": 1
    },

    "Menu 3": {
        "waffle": 1,
        "bacon": 1
    },

    "Menu 4": {
        "crab": 1,
        "lemon": 1,
        "slice_of_pie": 1
    },

    "Menu 5": {
        "slice_of_pizza": 1,
        "prawn": 1,
        "chocolate_chip_cookie": 1
    }
}

CONDIMENTS = {
    "tomato_ketchup_bottle": 1,
    "yellow_mustard_bottle": 1
}

def pretty_name(label):
    return display_label_name(label)

def print_menu_requirements():
    print("ROBOT RESTAURANT MENU REQUIREMENTS")
    print("==================================")

    for menu_name, required_items in MENU_REQUIREMENTS.items():
        readable = []
        for item, count in required_items.items():
            readable.append(f"{pretty_name(item)} x{count}")

        print(menu_name + ":", ", ".join(readable))

    print("\nAvailable condiments:")
    print(", ".join([pretty_name(x) for x in CONDIMENTS.keys()]))

print_menu_requirements()

# ============================================================
# Cell 17 — Function to detect people, objects, and tables from one capture
# ============================================================

def detect_one_restaurant_frame(frame):
    """
    Detects:
    - people using YOLOv8m
    - tables using YOLOv8m
    - special objects using YOLO-World + few-shot CLIP

    Returns:
    - people_count
    - table_count
    - occupied_tables
    - free_tables
    - object_detections
    - object_counts
    - annotated frame
    """

    frame = cv2.resize(frame, (640, 480))
    h, w = frame.shape[:2]

    # -----------------------------
    # A) People + table detection
    # -----------------------------

    people_table_results = people_table_model.predict(
        frame,
        conf=0.20,
        iou=0.45,
        imgsz=1280,
        device="cpu",
        verbose=False
    )

    raw_people = []
    raw_tables = []

    for r in people_table_results:
        for box in r.boxes:
            cls = int(box.cls[0])
            name = people_table_model.names[cls]
            conf = float(box.conf[0])
            xyxy = box.xyxy[0].cpu().numpy().astype(int).tolist()

            if name == "person":
                raw_people.append({
                    "class": "person",
                    "confidence": conf,
                    "box": xyxy
                })

            elif name == "dining table":
                raw_tables.append({
                    "final_label": "table",
                    "final_label_display": "table",
                    "decision_source": "YOLOv8m",
                    "yolo_label": "dining table",
                    "yolo_confidence": conf,
                    "box": xyxy
                })

    people_detections = clean_person_boxes(
        raw_people,
        frame_shape=frame.shape,
        iou_threshold=0.25,
        inside_threshold=0.50
    )

    table_detections = clean_duplicate_object_boxes(
        raw_tables,
        iou_threshold=0.40
    )

    used_fallback_table = False

    if len(table_detections) == 0:
        fallback_table_box = [
            int(w * 0.05),
            int(h * 0.58),
            int(w * 0.98),
            int(h * 0.98)
        ]

        table_detections.append({
            "final_label": "table",
            "final_label_display": "table",
            "decision_source": "fallback",
            "yolo_label": "fallback table area",
            "yolo_confidence": 1.0,
            "box": fallback_table_box
        })

        used_fallback_table = True

    # -----------------------------
    # B) Special object detection
    # -----------------------------

    object_results = object_model.predict(
        frame,
        conf=0.03,
        iou=0.45,
        imgsz=1280,
        device="cpu",
        verbose=False
    )

    SPECIAL_CLASSES = [
        "sandwich",
        "slice_of_pie",
        "hot_dog",
        "crisps",
        "chocolate_chip_cookie",
        "waffle",
        "bacon",
        "crab",
        "lemon",
        "slice_of_pizza",
        "prawn",
        "tomato_ketchup_bottle",
        "yellow_mustard_bottle"
    ]

    FEWSHOT_THRESHOLD = 0.78
    FEWSHOT_MARGIN = 0.05

    raw_object_detections = []

    for r in object_results:
        for box in r.boxes:
            cls_id = int(box.cls[0])
            yolo_conf = float(box.conf[0])
            xyxy = box.xyxy[0].cpu().numpy().astype(int).tolist()

            yolo_label_raw = object_results[0].names[cls_id]
            yolo_label_norm = normalize_item_name(yolo_label_raw)

            area_ratio = box_area_ratio(xyxy, frame)

            # Ignore very large boxes because they often include person/background
            if area_ratio > 0.35:
                continue

            crop = crop_box_from_frame(frame, xyxy, padding=8)

            fewshot_label = None
            fewshot_score = None
            fewshot_margin = None
            fewshot_top_scores = []

            final_label = yolo_label_norm
            decision_source = "YOLO-World"

            # Few-shot correction using your saved Drive examples
            if crop is not None and len(reference_embeddings) > 0:
                best_result, all_scores = classify_image_with_few_shot(crop, top_k=20)

                filtered_scores = [
                    (label, score)
                    for label, score in all_scores
                    if label in SPECIAL_CLASSES
                ]

                filtered_scores = sorted(filtered_scores, key=lambda x: x[1], reverse=True)
                fewshot_top_scores = filtered_scores[:5]

                if len(filtered_scores) > 0:
                    fewshot_label, fewshot_score = filtered_scores[0]

                    if len(filtered_scores) > 1:
                        fewshot_margin = fewshot_score - filtered_scores[1][1]
                    else:
                        fewshot_margin = fewshot_score

                    if fewshot_score >= FEWSHOT_THRESHOLD and fewshot_margin >= FEWSHOT_MARGIN:
                        final_label = fewshot_label
                        decision_source = "Few-shot CLIP"

            useful_label = final_label in SPECIAL_CLASSES or final_label == "bottle"

            if useful_label:
                raw_object_detections.append({
                    "final_label": final_label,
                    "final_label_display": display_label_name(final_label),
                    "decision_source": decision_source,
                    "yolo_label": yolo_label_raw,
                    "yolo_label_norm": yolo_label_norm,
                    "yolo_confidence": yolo_conf,
                    "fewshot_label": fewshot_label,
                    "fewshot_label_display": None if fewshot_label is None else display_label_name(fewshot_label),
                    "fewshot_score": fewshot_score,
                    "fewshot_margin": fewshot_margin,
                    "fewshot_top_scores": fewshot_top_scores,
                    "area_ratio": area_ratio,
                    "box": xyxy
                })

    object_detections = clean_duplicate_object_boxes(
        raw_object_detections,
        iou_threshold=0.35
    )

    object_counts = Counter([obj["final_label"] for obj in object_detections])

    # -----------------------------
    # C) Table occupation
    # -----------------------------

    table_statuses = []

    occupied_tables = 0
    free_tables = 0

    for idx, table in enumerate(table_detections):
        table_box = table["box"]

        occupied_by_person = is_person_near_table(table_box, people_detections)
        occupied_by_objects, objects_on_table = table_has_objects(table_box, object_detections)

        occupied = occupied_by_person or occupied_by_objects

        if occupied:
            status = "occupied"
            occupied_tables += 1
        else:
            status = "free"
            free_tables += 1

        table_statuses.append({
            "table_id": idx + 1,
            "status": status,
            "occupied_by_person": occupied_by_person,
            "occupied_by_objects": occupied_by_objects,
            "objects_on_table": objects_on_table,
            "box": table_box,
            "source": table["decision_source"]
        })

    people_count = len(people_detections)
    table_count = len(table_detections)

    return {
        "frame": frame,
        "people_detections": people_detections,
        "people_count": people_count,
        "table_detections": table_detections,
        "table_statuses": table_statuses,
        "table_count": table_count,
        "occupied_tables": occupied_tables,
        "free_tables": free_tables,
        "object_detections": object_detections,
        "object_counts": object_counts,
        "used_fallback_table": used_fallback_table
    }

# ============================================================
# Cell 18 — Check which menu is completed
# ============================================================

def check_menu_completion(cumulative_object_counts):
    """
    Checks all menus against cumulative detected object counts.
    """

    menu_results = {}

    for menu_name, required_items in MENU_REQUIREMENTS.items():
        missing_items = {}
        completed_items = {}

        for item, required_count in required_items.items():
            detected_count = cumulative_object_counts.get(item, 0)

            if detected_count >= required_count:
                completed_items[item] = detected_count
            else:
                missing_items[item] = required_count - detected_count

        is_complete = len(missing_items) == 0

        menu_results[menu_name] = {
            "complete": is_complete,
            "missing": missing_items,
            "completed": completed_items
        }

    return menu_results


def print_cumulative_result(cumulative_object_counts, latest_people_count=None, latest_occupied_tables=None, latest_free_tables=None):
    """
    Prints clean final cumulative result.
    """

    total_objects = sum(cumulative_object_counts.values())

    print("\nCURRENT CUMULATIVE RESULT")
    print("=========================")

    if latest_people_count is not None:
        print(f"people: {latest_people_count}")

    print(f"objects count: {total_objects}")

    if total_objects == 0:
        print("objects: none")
    else:
        readable_objects = []
        for label, count in cumulative_object_counts.items():
            readable_objects.append(f"{pretty_name(label)}: {count}")

        print("objects:", ", ".join(readable_objects))

    if latest_occupied_tables is not None:
        print(f"table occupied: {latest_occupied_tables}")

    if latest_free_tables is not None:
        print(f"free table: {latest_free_tables}")

    print("\nMENU COMPLETION")
    print("===============")

    menu_results = check_menu_completion(cumulative_object_counts)

    for menu_name, result in menu_results.items():
        if result["complete"]:
            print(f"{menu_name}: COMPLETE")
        else:
            missing_readable = []
            for item, missing_count in result["missing"].items():
                missing_readable.append(f"{pretty_name(item)} x{missing_count}")

            print(f"{menu_name}: not complete | missing: {', '.join(missing_readable)}")

    complete_menus = [
        menu_name
        for menu_name, result in menu_results.items()
        if result["complete"]
    ]

    print("\nCompleted menus:", complete_menus if complete_menus else "none")

    return menu_results

# ============================================================
# Cell 19 — Capture objects one by one until finish
# ============================================================

cumulative_object_counts = Counter()
capture_history = []

capture_number = 1

print("Starting one-by-one capture.")
print("After each capture, type:")
print("- press Enter to continue")
print("- type finish to stop")
print("- type reset to clear all counts")
print("====================================")

while True:
    user_command = input("\nPress Enter to capture next image, or type finish/reset: ").strip().lower()

    if user_command == "finish":
        print("\nStopping capture loop.")
        break

    if user_command == "reset":
        cumulative_object_counts = Counter()
        capture_history = []
        capture_number = 1
        print("Counts reset.")
        continue

    print(f"\nCapturing image {capture_number}...")

    image_path = f"/content/restaurant_capture_{capture_number}.jpg"
    filename = take_photo(image_path)

    frame = cv2.imread(filename)

    if frame is None:
        print("Image was not captured correctly. Try again.")
        continue

    result = detect_one_restaurant_frame(frame)

    object_detections = result["object_detections"]
    object_counts_this_capture = result["object_counts"]

    people_count = result["people_count"]
    occupied_tables = result["occupied_tables"]
    free_tables = result["free_tables"]

    # Add this capture's detected objects to cumulative counts
    cumulative_object_counts.update(object_counts_this_capture)

    capture_history.append({
        "capture_number": capture_number,
        "image_path": image_path,
        "people_count": people_count,
        "occupied_tables": occupied_tables,
        "free_tables": free_tables,
        "object_counts": dict(object_counts_this_capture)
    })

    print("\nTHIS CAPTURE RESULT")
    print("===================")
    print(f"people: {people_count}")

    if len(object_counts_this_capture) == 0:
        print("objects detected in this capture: none")
    else:
        readable_this_capture = []
        for label, count in object_counts_this_capture.items():
            readable_this_capture.append(f"{pretty_name(label)}: {count}")

        print("objects detected in this capture:", ", ".join(readable_this_capture))

    print(f"table occupied: {occupied_tables}")
    print(f"free table: {free_tables}")

    # Print cumulative result and menu completion
    menu_results = print_cumulative_result(
        cumulative_object_counts,
        latest_people_count=people_count,
        latest_occupied_tables=occupied_tables,
        latest_free_tables=free_tables
    )

    # Draw clean image for this capture
    frame_draw = result["frame"].copy()

    # Draw people
    for p in result["people_detections"]:
        x1, y1, x2, y2 = p["box"]
        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            frame_draw,
            f"person {p['confidence']:.2f}",
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (0, 255, 0),
            2
        )

    # Draw objects
    for obj in result["object_detections"]:
        x1, y1, x2, y2 = obj["box"]

        if obj["fewshot_score"] is not None:
            score = obj["fewshot_score"]
        else:
            score = obj["yolo_confidence"]

        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (255, 0, 255), 2)
        cv2.putText(
            frame_draw,
            f"{obj['final_label_display']} {score:.2f}",
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (255, 0, 255),
            2
        )

    # Draw table statuses
    for t in result["table_statuses"]:
        x1, y1, x2, y2 = t["box"]

        if t["status"] == "occupied":
            color = (0, 0, 255)
            table_text = f"Table {t['table_id']}: occupied"
        else:
            color = (0, 255, 255)
            table_text = f"Table {t['table_id']}: free"

        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), color, 2)
        cv2.putText(
            frame_draw,
            table_text,
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            color,
            2
        )

    # Show image
    frame_rgb = cv2.cvtColor(frame_draw, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(12, 8))
    plt.imshow(frame_rgb)
    plt.axis("off")
    plt.title(f"Capture {capture_number}")
    plt.show()

    capture_number += 1

print("\nFINAL RESULT AFTER ALL CAPTURES")
print("===============================")

final_menu_results = print_cumulative_result(cumulative_object_counts)

print("\nCapture history:")
for item in capture_history:
    print(item)

# ============================================================
# Cell 20 — Show final object counts and menu status as tables
# ============================================================

# Object count table
object_table_rows = []

for label, count in cumulative_object_counts.items():
    object_table_rows.append({
        "object": pretty_name(label),
        "count": count
    })

object_df = pd.DataFrame(object_table_rows)

if len(object_df) == 0:
    print("No objects detected.")
else:
    print("Final object counts:")
    display(object_df)

# Menu completion table
menu_rows = []

final_menu_results = check_menu_completion(cumulative_object_counts)

for menu_name, result in final_menu_results.items():
    if result["complete"]:
        missing_text = "none"
    else:
        missing_text = ", ".join([
            f"{pretty_name(item)} x{count}"
            for item, count in result["missing"].items()
        ])

    menu_rows.append({
        "menu": menu_name,
        "complete": result["complete"],
        "missing": missing_text
    })

menu_df = pd.DataFrame(menu_rows)

print("\nMenu completion:")
display(menu_df)

# ============================================================
# Cell 19 — Capture objects one by one until finish
# ============================================================

cumulative_object_counts = Counter()
capture_history = []

capture_number = 1

print("Starting one-by-one capture.")
print("After each capture, type:")
print("- press Enter to continue")
print("- type finish to stop")
print("- type reset to clear all counts")
print("====================================")

while True:
    user_command = input("\nPress Enter to capture next image, or type finish/reset: ").strip().lower()

    if user_command == "finish":
        print("\nStopping capture loop.")
        break

    if user_command == "reset":
        cumulative_object_counts = Counter()
        capture_history = []
        capture_number = 1
        print("Counts reset.")
        continue

    print(f"\nCapturing image {capture_number}...")

    image_path = f"/content/restaurant_capture_{capture_number}.jpg"
    filename = take_photo(image_path)

    frame = cv2.imread(filename)

    if frame is None:
        print("Image was not captured correctly. Try again.")
        continue

    result = detect_one_restaurant_frame(frame)

    object_detections = result["object_detections"]
    object_counts_this_capture = result["object_counts"]

    people_count = result["people_count"]
    occupied_tables = result["occupied_tables"]
    free_tables = result["free_tables"]

    # Add this capture's detected objects to cumulative counts
    cumulative_object_counts.update(object_counts_this_capture)

    capture_history.append({
        "capture_number": capture_number,
        "image_path": image_path,
        "people_count": people_count,
        "occupied_tables": occupied_tables,
        "free_tables": free_tables,
        "object_counts": dict(object_counts_this_capture)
    })

    print("\nTHIS CAPTURE RESULT")
    print("===================")
    print(f"people: {people_count}")

    if len(object_counts_this_capture) == 0:
        print("objects detected in this capture: none")
    else:
        readable_this_capture = []
        for label, count in object_counts_this_capture.items():
            readable_this_capture.append(f"{pretty_name(label)}: {count}")

        print("objects detected in this capture:", ", ".join(readable_this_capture))

    print(f"table occupied: {occupied_tables}")
    print(f"free table: {free_tables}")

    # Print cumulative result and menu completion
    menu_results = print_cumulative_result(
        cumulative_object_counts,
        latest_people_count=people_count,
        latest_occupied_tables=occupied_tables,
        latest_free_tables=free_tables
    )

    # Draw clean image for this capture
    frame_draw = result["frame"].copy()

    # Draw people
    for p in result["people_detections"]:
        x1, y1, x2, y2 = p["box"]
        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.putText(
            frame_draw,
            f"person {p['confidence']:.2f}",
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (0, 255, 0),
            2
        )

    # Draw objects
    for obj in result["object_detections"]:
        x1, y1, x2, y2 = obj["box"]

        if obj["fewshot_score"] is not None:
            score = obj["fewshot_score"]
        else:
            score = obj["yolo_confidence"]

        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (255, 0, 255), 2)
        cv2.putText(
            frame_draw,
            f"{obj['final_label_display']} {score:.2f}",
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            (255, 0, 255),
            2
        )

    # Draw table statuses
    for t in result["table_statuses"]:
        x1, y1, x2, y2 = t["box"]

        if t["status"] == "occupied":
            color = (0, 0, 255)
            table_text = f"Table {t['table_id']}: occupied"
        else:
            color = (0, 255, 255)
            table_text = f"Table {t['table_id']}: free"

        cv2.rectangle(frame_draw, (x1, y1), (x2, y2), color, 2)
        cv2.putText(
            frame_draw,
            table_text,
            (x1, max(y1 - 8, 20)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.55,
            color,
            2
        )

    # Show image
    frame_rgb = cv2.cvtColor(frame_draw, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(12, 8))
    plt.imshow(frame_rgb)
    plt.axis("off")
    plt.title(f"Capture {capture_number}")
    plt.show()

    capture_number += 1

print("\nFINAL RESULT AFTER ALL CAPTURES")
print("===============================")

final_menu_results = print_cumulative_result(cumulative_object_counts)

print("\nCapture history:")
for item in capture_history:
    print(item)

# ============================================================
# Cell 20 — Show final object counts and menu status as tables
# ============================================================

# Object count table
object_table_rows = []

for label, count in cumulative_object_counts.items():
    object_table_rows.append({
        "object": pretty_name(label),
        "count": count
    })

object_df = pd.DataFrame(object_table_rows)

if len(object_df) == 0:
    print("No objects detected.")
else:
    print("Final object counts:")
    display(object_df)

# Menu completion table
menu_rows = []

final_menu_results = check_menu_completion(cumulative_object_counts)

for menu_name, result in final_menu_results.items():
    if result["complete"]:
        missing_text = "none"
    else:
        missing_text = ", ".join([
            f"{pretty_name(item)} x{count}"
            for item, count in result["missing"].items()
        ])

    menu_rows.append({
        "menu": menu_name,
        "complete": result["complete"],
        "missing": missing_text
    })

menu_df = pd.DataFrame(menu_rows)

print("\nMenu completion:")
display(menu_df)

# ============================================================
# People Count Only — using already loaded code/model
# ============================================================

# Capture photo
filename = take_photo("/content/people_count_only.jpg")

# Read image
frame = cv2.imread(filename)

if frame is None:
    raise ValueError("Image was not captured correctly. Please run the cell again.")

frame = cv2.resize(frame, (640, 480))

# Detect only people using the already loaded YOLOv8m model
results = people_table_model.predict(
    frame,
    conf=0.25,
    iou=0.45,
    imgsz=1280,
    device="cpu",
    classes=[0],   # COCO class 0 = person
    verbose=False
)

raw_people = []

for box in results[0].boxes:
    conf = float(box.conf[0])
    xyxy = box.xyxy[0].cpu().numpy().astype(int).tolist()

    raw_people.append({
        "class": "person",
        "confidence": conf,
        "box": xyxy
    })

# Remove duplicate boxes for the same person
people_detections = clean_person_boxes(
    raw_people,
    frame_shape=frame.shape,
    iou_threshold=0.25,
    inside_threshold=0.50
)

# Final count
people_count = len(people_detections)

# Clean output variable
people_count_output = {
    "people": people_count,
    "raw_person_detections": len(raw_people),
    "final_person_detections": len(people_detections)
}

print("PEOPLE COUNT RESULT")
print("===================")
print(f"people: {people_count}")

print("\nFull output dictionary:")
print(people_count_output)

for i, person in enumerate(people_detections, start=1):
    print(f"person {i} | confidence: {person['confidence']:.3f} | box: {person['box']}")

# Draw result
frame_draw = frame.copy()

for i, person in enumerate(people_detections, start=1):
    x1, y1, x2, y2 = person["box"]
    conf = person["confidence"]

    cv2.rectangle(frame_draw, (x1, y1), (x2, y2), (0, 255, 0), 2)

    cv2.putText(
        frame_draw,
        f"person {i} {conf:.2f}",
        (x1, max(y1 - 8, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.6,
        (0, 255, 0),
        2
    )

cv2.putText(
    frame_draw,
    f"People: {people_count}",
    (20, 40),
    cv2.FONT_HERSHEY_SIMPLEX,
    1.0,
    (255, 255, 255),
    3
)

frame_rgb = cv2.cvtColor(frame_draw, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(12, 8))
plt.imshow(frame_rgb)
plt.axis("off")
plt.show()

# This is the final direct output you can use in other parts of your code
people_count

"""calling from vision"""

# ============================================================
# Cell 1 — Load YOLO Pose model for hand-calling detection
# ============================================================

from ultralytics import YOLO
import cv2
import numpy as np
import matplotlib.pyplot as plt

# YOLO pose model detects people and body keypoints
pose_model = YOLO("yolov8m-pose.pt")

print("YOLO pose model loaded.")

# ============================================================
# Cell 2 — Record short webcam video
# ============================================================

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def record_video(filename="/content/hand_call_test.webm", duration_seconds=4):
    js = Javascript(f'''
        async function recordVideo() {{
            const div = document.createElement('div');

            const instruction = document.createElement('p');
            instruction.textContent = 'Recording will start. Raise/wave your hand if you are calling the robot.';
            instruction.style.fontSize = '18px';
            instruction.style.fontWeight = 'bold';
            div.appendChild(instruction);

            const video = document.createElement('video');
            video.style.display = 'block';
            video.style.maxWidth = '640px';
            div.appendChild(video);

            document.body.appendChild(div);

            const stream = await navigator.mediaDevices.getUserMedia({{video: true, audio: false}});
            video.srcObject = stream;
            await video.play();

            const recorder = new MediaRecorder(stream);
            let chunks = [];

            recorder.ondataavailable = e => chunks.push(e.data);

            recorder.start();

            await new Promise(resolve => setTimeout(resolve, {duration_seconds * 1000}));

            recorder.stop();

            await new Promise(resolve => recorder.onstop = resolve);

            stream.getVideoTracks()[0].stop();

            const blob = new Blob(chunks, {{type: 'video/webm'}});
            const reader = new FileReader();

            const base64data = await new Promise(resolve => {{
                reader.onloadend = () => resolve(reader.result);
                reader.readAsDataURL(blob);
            }});

            div.remove();

            return base64data;
        }}
    ''')

    display(js)
    data = eval_js("recordVideo()")

    binary = b64decode(data.split(",")[1])

    with open(filename, "wb") as f:
        f.write(binary)

    return filename


video_path = record_video("/content/hand_call_test.webm", duration_seconds=4)

print("Video saved to:")
print(video_path)

# ============================================================
# Cell 3 — Helper functions for person tracking and waving
# ============================================================

def box_center(box):
    x1, y1, x2, y2 = box
    return np.array([(x1 + x2) / 2, (y1 + y2) / 2])


def assign_person_id(box, active_tracks, max_distance=120):
    """
    Assigns a detected person to an existing track based on nearest box center.
    If no close track exists, creates a new person id.
    """

    center = box_center(box)

    best_id = None
    best_dist = float("inf")

    for person_id, track in active_tracks.items():
        last_center = track["last_center"]
        dist = np.linalg.norm(center - last_center)

        if dist < best_dist:
            best_dist = dist
            best_id = person_id

    if best_id is not None and best_dist < max_distance:
        return best_id

    new_id = len(active_tracks)
    return new_id


def count_direction_changes(values, min_step=8):
    """
    Counts left-right movement changes.
    """

    if len(values) < 4:
        return 0

    directions = []

    for i in range(1, len(values)):
        diff = values[i] - values[i - 1]

        if abs(diff) >= min_step:
            directions.append(np.sign(diff))

    if len(directions) < 2:
        return 0

    changes = 0

    for i in range(1, len(directions)):
        if directions[i] != directions[i - 1]:
            changes += 1

    return changes

# ============================================================
# Cell 4 — Detect people calling by raised/waving hand using YOLO Pose
# ============================================================

cap = cv2.VideoCapture(video_path)

if not cap.isOpened():
    raise ValueError("Could not open recorded video.")

frames = []
active_tracks = {}

frame_index = 0

# COCO keypoint indexes used by YOLO pose:
# 0 = nose
# 5 = left shoulder
# 6 = right shoulder
# 9 = left wrist
# 10 = right wrist

while True:
    ret, frame = cap.read()

    if not ret:
        break

    frame = cv2.resize(frame, (640, 480))
    frames.append(frame.copy())

    results = pose_model.predict(
        frame,
        conf=0.25,
        iou=0.45,
        imgsz=640,
        device="cpu",
        verbose=False
    )

    if len(results[0].boxes) == 0:
        frame_index += 1
        continue

    boxes = results[0].boxes.xyxy.cpu().numpy()
    confs = results[0].boxes.conf.cpu().numpy()

    if results[0].keypoints is None:
        frame_index += 1
        continue

    keypoints_xy = results[0].keypoints.xy.cpu().numpy()
    keypoints_conf = results[0].keypoints.conf.cpu().numpy()

    for det_idx, box in enumerate(boxes):
        conf = confs[det_idx]
        x1, y1, x2, y2 = box.astype(int).tolist()

        person_box = [x1, y1, x2, y2]
        person_h = max(1, y2 - y1)

        person_id = assign_person_id(person_box, active_tracks)

        if person_id not in active_tracks:
            active_tracks[person_id] = {
                "last_center": box_center(person_box),
                "boxes": [],
                "confidences": [],
                "left_wrist_x": [],
                "right_wrist_x": [],
                "raised_frames": 0,
                "seen_frames": 0
            }

        track = active_tracks[person_id]
        track["last_center"] = box_center(person_box)
        track["boxes"].append(person_box)
        track["confidences"].append(conf)
        track["seen_frames"] += 1

        kxy = keypoints_xy[det_idx]
        kconf = keypoints_conf[det_idx]

        # Keypoints
        left_shoulder = kxy[5]
        right_shoulder = kxy[6]
        left_wrist = kxy[9]
        right_wrist = kxy[10]

        left_shoulder_conf = kconf[5]
        right_shoulder_conf = kconf[6]
        left_wrist_conf = kconf[9]
        right_wrist_conf = kconf[10]

        shoulder_y_values = []

        if left_shoulder_conf > 0.30:
            shoulder_y_values.append(left_shoulder[1])

        if right_shoulder_conf > 0.30:
            shoulder_y_values.append(right_shoulder[1])

        if len(shoulder_y_values) > 0:
            shoulder_y = np.mean(shoulder_y_values)
        else:
            shoulder_y = y1 + 0.35 * person_h

        hand_raised_this_frame = False

        # Left wrist
        if left_wrist_conf > 0.30:
            lx, ly = left_wrist
            track["left_wrist_x"].append(float(lx))

            # In image coordinates, smaller y means higher
            if ly < shoulder_y + 0.15 * person_h:
                hand_raised_this_frame = True

        # Right wrist
        if right_wrist_conf > 0.30:
            rx, ry = right_wrist
            track["right_wrist_x"].append(float(rx))

            if ry < shoulder_y + 0.15 * person_h:
                hand_raised_this_frame = True

        if hand_raised_this_frame:
            track["raised_frames"] += 1

    frame_index += 1

cap.release()

print("Processed frames:", len(frames))
print("Tracked people:", len(active_tracks))

# ============================================================
# Cell 5 — Analyse raised hand + waving motion
# ============================================================

calling_people = []

for person_id, track in active_tracks.items():
    seen_frames = track["seen_frames"]
    raised_frames = track["raised_frames"]

    raised_ratio = raised_frames / max(1, seen_frames)

    left_x = track["left_wrist_x"]
    right_x = track["right_wrist_x"]

    left_range = max(left_x) - min(left_x) if len(left_x) >= 2 else 0
    right_range = max(right_x) - min(right_x) if len(right_x) >= 2 else 0

    left_changes = count_direction_changes(left_x, min_step=8)
    right_changes = count_direction_changes(right_x, min_step=8)

    max_x_range = max(left_range, right_range)
    max_direction_changes = max(left_changes, right_changes)

    # Rules for calling/waving
    is_hand_raised = raised_ratio >= 0.25
    is_waving = max_x_range >= 30 and max_direction_changes >= 1

    is_calling = is_hand_raised and is_waving

    track["raised_ratio"] = raised_ratio
    track["max_x_range"] = max_x_range
    track["max_direction_changes"] = max_direction_changes
    track["is_calling"] = is_calling

    if is_calling:
        calling_people.append(person_id)

people_calling_count = len(calling_people)

print("HAND CALL DETECTION RESULT")
print("==========================")
print(f"people calling: {people_calling_count}")

for person_id, track in active_tracks.items():
    print()
    print(f"person {person_id + 1}")
    print("seen frames:", track["seen_frames"])
    print("raised ratio:", round(track["raised_ratio"], 2))
    print("wrist x movement range:", round(track["max_x_range"], 1))
    print("direction changes:", track["max_direction_changes"])
    print("calling:", track["is_calling"])

# clean output variable
people_calling_output = {
    "people_calling": people_calling_count,
    "tracked_people": len(active_tracks)
}

people_calling_output

# ============================================================
# Cell 6 — Draw final calling result
# ============================================================

if len(frames) == 0:
    raise ValueError("No video frames found.")

final_frame = frames[-1].copy()

for person_id, track in active_tracks.items():
    if len(track["boxes"]) == 0:
        continue

    # Use the last box for drawing
    x1, y1, x2, y2 = track["boxes"][-1]

    if track["is_calling"]:
        color = (0, 0, 255)
        label = "CALLING"
    else:
        color = (0, 255, 0)
        label = "person"

    cv2.rectangle(final_frame, (x1, y1), (x2, y2), color, 2)

    cv2.putText(
        final_frame,
        f"{label} {person_id + 1}",
        (x1, max(y1 - 10, 20)),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.7,
        color,
        2
    )

cv2.putText(
    final_frame,
    f"People calling: {people_calling_count}",
    (20, 40),
    cv2.FONT_HERSHEY_SIMPLEX,
    1.0,
    (255, 255, 255),
    3
)

final_rgb = cv2.cvtColor(final_frame, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(12, 8))
plt.imshow(final_rgb)
plt.axis("off")
plt.show()